"""changed user email type to EmailStr

Revision ID: 0bca431e3df4
Revises: 94307f8efb87
Create Date: 2025-05-09 12:57:10.856159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bca431e3df4'
down_revision: Union[str, None] = '94307f8efb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_index('email', table_name='waitlist_subscribers')
    op.drop_index('ix_waitlist_subscribers_id', table_name='waitlist_subscribers')
    op.drop_table('waitlist_subscribers')
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('phone', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address_line1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address_line2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_birth', mysql.DATETIME(), nullable=True),
    sa.Column('privacy_preference', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('profile_picture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('phone', 'users', ['phone'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('waitlist_subscribers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_waitlist_subscribers_id', 'waitlist_subscribers', ['id'], unique=False)
    op.create_index('email', 'waitlist_subscribers', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='refresh_tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
