"""edited phone field type

Revision ID: 4a8b8b3476db
Revises: dec90a8341dc
Create Date: 2025-05-07 13:51:08.825866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a8b8b3476db'
down_revision: Union[str, None] = 'dec90a8341dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
