""" 

Revision ID: 6815b0753874
Revises: db62c8106672
Create Date: 2025-05-09 18:22:01.082919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6815b0753874'
down_revision: Union[str, None] = 'db62c8106672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_ibfk_1', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_email'], ['email'])
    op.drop_column('users', 'signinoption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signinoption', mysql.VARCHAR(length=15), nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_ibfk_1', 'refresh_tokens', 'users', ['user_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
