"""Added signinoption field to User model

Revision ID: db62c8106672
Revises: bb74b29e1708
Create Date: 2025-05-09 17:18:32.195075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db62c8106672'
down_revision: Union[str, None] = 'bb74b29e1708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_ibfk_1', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_email'], ['email'])
    op.add_column('users', sa.Column('signinoption', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signinoption')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_ibfk_1', 'refresh_tokens', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###
